### ISSUE TITLE
README: simple install procedures

### ISSUE THREAD

**Issue by vielmetti** [hishamhm/lua-mastodon#3]
The README should have at least a simple paragraph about what Lua is, how one might install it, and how one might test that this package works.

I'm doing `apt-get install lua5.2` on Ubuntu 16.04 ARM64 and hoping for the best! At least one issue there which I'll address separately.

**Comment by hishamhm** [comment]
The install procedure will be `luarocks install lua-mastodon` tomorrow :)

**Comment by vielmetti** [comment]
`Error: No results matching query were found.` if you are too eager to get this prerelease! I will wait.

**Comment by hishamhm** [comment]
Done! The initial release is out. :)

**Comment by vielmetti** [comment]
Install worked, as far as I can tell, but it's not clear how to run this thing....what command line do I use to exercise this?

**Comment by hishamhm** [comment]
Check the example.lua script for an usage example. I haven't really tested
the code beyond what's there for now. This is brand new code.
